### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [ElenaCid/prj-rev-bwfs-dasmoto#7]
Satisfactory

Good job reproducing the design mock we provided.

Make sure to go back and write your code more effectively. Adhere to style conventions so that your code is easy for another programmer (or your future self) to read. Use `div` tags with adequate class names to properly divide your page into logical sections.

**Comment by ElenaCid** [comment]
Hello Steve,

I fixed the issues that you brought up. Could you please take a look at the fixes and let me know what you think?

Elena
